/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'

export class AccountSchema extends BaseModel {
  static $columns = ['accessToken', 'accessTokenExpiresAt', 'accountId', 'createdAt', 'id', 'idToken', 'password', 'providerId', 'refreshToken', 'refreshTokenExpiresAt', 'scope', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accessToken: string | null
  @column()
  declare accessTokenExpiresAt: number | null
  @column()
  declare accountId: string
  @column()
  declare createdAt: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idToken: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column()
  declare refreshTokenExpiresAt: number | null
  @column()
  declare scope: string | null
  @column()
  declare updatedAt: number
  @column()
  declare userId: string
}

export class SessionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'ipAddress', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare createdAt: number
  @column()
  declare expiresAt: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare token: string
  @column()
  declare updatedAt: number
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerified', 'id', 'image', 'name', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare createdAt: number
  @column()
  declare email: string
  @column()
  declare emailVerified: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare name: string
  @column()
  declare updatedAt: number
}

export class VerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'identifier', 'updatedAt', 'value'] as const
  $columns = VerificationSchema.$columns
  @column()
  declare createdAt: number | null
  @column()
  declare expiresAt: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifier: string
  @column()
  declare updatedAt: number | null
  @column()
  declare value: string
}
