/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaMarkerSchema extends BaseModel {
  static $columns = ['createdAt', 'endTime', 'id', 'markerType', 'startTime', 'tmdbId', 'updatedAt'] as const
  $columns = MediaMarkerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endTime: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare markerType: string
  @column()
  declare startTime: number
  @column()
  declare tmdbId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfileInterestSchema extends BaseModel {
  static $columns = ['affinityScore', 'createdAt', 'genreId', 'id', 'lastWatchedAt', 'profileId', 'updatedAt'] as const
  $columns = ProfileInterestSchema.$columns
  @column()
  declare affinityScore: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare genreId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastWatchedAt: DateTime | null
  @column()
  declare profileId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfileSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'id', 'isKids', 'name', 'preferences', 'updatedAt', 'userId'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isKids: boolean
  @column()
  declare name: string
  @column()
  declare preferences: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WatchHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'currentTime', 'episodeNum', 'id', 'isFinished', 'mediaType', 'profileId', 'seasonNum', 'tmdbId', 'totalDuration', 'updatedAt'] as const
  $columns = WatchHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentTime: number
  @column()
  declare episodeNum: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isFinished: boolean
  @column()
  declare mediaType: string
  @column()
  declare profileId: number
  @column()
  declare seasonNum: number | null
  @column()
  declare tmdbId: string
  @column()
  declare totalDuration: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
