/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Download: () => import('#controllers/download_controller'),
  Home: () => import('#controllers/home_controller'),
  Media: () => import('#controllers/media_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  People: () => import('#controllers/people_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
  Progress: () => import('#controllers/progress_controller'),
  Streaming: () => import('#controllers/streaming_controller'),
  Subtitles: () => import('#controllers/subtitles_controller'),
  Transcode: () => import('#controllers/transcode_controller'),
  Watchlist: () => import('#controllers/watchlist_controller'),
}
