name: jojoflix_app
description: JojoFlix — Plateforme de streaming VOD self-hosted multiplateforme
publish_to: 'none'
version: 1.0.7+7

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Video player
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

  # Images & cache
  cached_network_image: ^3.4.1

  # Storage
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5

  # HTTP client
  dio: ^5.8.0

  # Trailer YouTube intégré
  youtube_explode_dart: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.14

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
