name: jojoflix_app
description: JojoFlix — Plateforme de streaming VOD self-hosted multiplateforme
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Video player
  media_kit: ^1.1.11
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.5

  # Images & cache
  cached_network_image: ^3.4.1

  # Storage
  shared_preferences: ^2.3.5

  # HTTP client
  dio: ^5.8.0

  # URL launcher (bandes annonces YouTube)
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.14

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
