networks:
  caddy:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jojoflix-api
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      NODE_ENV: production
      DB_PATH: /data/jojoflix.sqlite
    image: jojoflix-api-api:v3
    labels:
      traefik.enable: "true"
      traefik.http.routers.jojoflix.rule: "Host(`jojoflixapi.jojoserv.com`)"
      traefik.http.routers.jojoflix.entrypoints: "websecure"
      traefik.http.routers.jojoflix.tls.certresolver: "letsencrypt"
      traefik.http.services.jojoflix.loadbalancer.server.port: "3333"
      traefik.docker.network: "caddy"
    networks:
      - caddy
    restart: unless-stopped
    volumes:
      - jojoflix_sqlite_data:/data

volumes:
  jojoflix_sqlite_data:
